# Generated by Django 6.0.6 on 2026-07-19 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MAutor',
            fields=[
                ('id_autor', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_autor', models.CharField(db_collation='Modern_Spanish_CI_AS', max_length=100)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('bibliografia', models.CharField(blank=True, db_collation='Modern_Spanish_CI_AS', max_length=500, null=True)),
            ],
            options={
                'db_table': 'M_AUTOR',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MBibliotecario',
            fields=[
                ('id_bibliotecario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_collation='Modern_Spanish_CI_AS', max_length=80)),
                ('correo', models.CharField(db_collation='Modern_Spanish_CI_AS', max_length=80, unique=True)),
                ('apellido', models.CharField(db_collation='Modern_Spanish_CI_AS', max_length=100)),
                ('telefono', models.CharField(blank=True, db_collation='Modern_Spanish_CI_AS', max_length=15, null=True)),
                ('fecha_contratacion', models.DateField()),
                ('estado', models.CharField(db_collation='Modern_Spanish_CI_AS', max_length=20)),
            ],
            options={
                'db_table': 'M_BIBLIOTECARIO',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MEjemplar',
            fields=[
                ('id_ejemplar', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_adquisicion', models.DateField()),
                ('numero_serie', models.CharField(db_collation='Modern_Spanish_CI_AS', max_length=30, unique=True)),
            ],
            options={
                'db_table': 'M_EJEMPLAR',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MLibro',
            fields=[
                ('id_libro', models.AutoField(primary_key=True, serialize=False)),
                ('titulo_libro', models.CharField(db_collation='Modern_Spanish_CI_AS', max_length=150)),
                ('isbn', models.CharField(db_collation='Modern_Spanish_CI_AS', max_length=20, unique=True)),
                ('anio_publicacion', models.IntegerField(blank=True, null=True)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'M_LIBRO',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MUsuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nombres', models.CharField(db_collation='Modern_Spanish_CI_AS', max_length=80)),
                ('apellidos', models.CharField(db_collation='Modern_Spanish_CI_AS', max_length=80)),
                ('password', models.CharField(db_collation='Modern_Spanish_CI_AS', max_length=250)),
                ('edad', models.IntegerField(blank=True, null=True)),
                ('email', models.CharField(db_collation='Modern_Spanish_CI_AS', max_length=100, unique=True)),
                ('telefono', models.CharField(blank=True, db_collation='Modern_Spanish_CI_AS', max_length=15, null=True)),
                ('dni', models.CharField(db_collation='Modern_Spanish_CI_AS', db_column='DNI', max_length=15, unique=True)),
            ],
            options={
                'db_table': 'M_USUARIO',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PCategoria',
            fields=[
                ('id_categoria', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_collation='Modern_Spanish_CI_AS', max_length=50)),
                ('descripcion', models.CharField(blank=True, db_collation='Modern_Spanish_CI_AS', max_length=200, null=True)),
            ],
            options={
                'db_table': 'P_CATEGORIA',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PEstado',
            fields=[
                ('id_estado', models.AutoField(primary_key=True, serialize=False)),
                ('entidad', models.CharField(db_collation='Modern_Spanish_CI_AS', max_length=30)),
                ('codigo', models.CharField(db_collation='Modern_Spanish_CI_AS', max_length=40)),
                ('descripcion', models.CharField(blank=True, db_collation='Modern_Spanish_CI_AS', max_length=100, null=True)),
            ],
            options={
                'db_table': 'P_ESTADO',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PMetodoPago',
            fields=[
                ('id_metodo_pago', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(db_collation='Modern_Spanish_CI_AS', max_length=100)),
            ],
            options={
                'db_table': 'P_METODO_PAGO',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PNacionalidad',
            fields=[
                ('id_nacionalidad', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_nacionalidad', models.CharField(db_collation='Modern_Spanish_CI_AS', max_length=50)),
            ],
            options={
                'db_table': 'P_NACIONALIDAD',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PTipoMulta',
            fields=[
                ('id_tipo_multa', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(db_collation='Modern_Spanish_CI_AS', max_length=100)),
            ],
            options={
                'db_table': 'P_TIPO_MULTA',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RLibroAutor',
            fields=[
                ('pk', models.CompositePrimaryKey('id_libro', 'id_autor', blank=True, editable=False, primary_key=True, serialize=False)),
                ('rol', models.CharField(blank=True, db_collation='Modern_Spanish_CI_AS', max_length=40, null=True)),
            ],
            options={
                'db_table': 'R_LIBRO_AUTOR',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sysdiagrams',
            fields=[
                ('name', models.CharField(db_collation='Modern_Spanish_CI_AS', max_length=128)),
                ('principal_id', models.IntegerField()),
                ('diagram_id', models.AutoField(primary_key=True, serialize=False)),
                ('version', models.IntegerField(blank=True, null=True)),
                ('definition', models.BinaryField(blank=True, max_length='max', null=True)),
            ],
            options={
                'db_table': 'sysdiagrams',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TDetallePrestamo',
            fields=[
                ('id_detalle', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'T_DETALLE_PRESTAMO',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TDevolucion',
            fields=[
                ('id_devolucion', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_devolucion_real', models.DateField()),
                ('dias_atraso', models.IntegerField()),
            ],
            options={
                'db_table': 'T_DEVOLUCION',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TMulta',
            fields=[
                ('id_multa', models.AutoField(primary_key=True, serialize=False)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
            options={
                'db_table': 'T_MULTA',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TPagoMulta',
            fields=[
                ('id_pago', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_pago', models.DateField()),
                ('monto_pagado', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
            options={
                'db_table': 'T_PAGO_MULTA',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TPrestamo',
            fields=[
                ('id_prestamo', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_prestamo', models.DateField()),
                ('fecha_devolucion_esperada', models.DateField()),
            ],
            options={
                'db_table': 'T_PRESTAMO',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TReserva',
            fields=[
                ('id_reserva', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_reserva', models.DateTimeField()),
                ('fecha_vencimiento', models.DateField()),
            ],
            options={
                'db_table': 'T_RESERVA',
                'managed': False,
            },
        ),
    ]
